#!/bin/bash

set -eux

# setup worker/pid dirs, not versioned
mkdir -p ${SNAP_COMMON}/var/run/spark/work

# setup log/history dirs, versioned
mkdir -p ${SNAP_DATA}/var/log/spark/apps

# setup spark config, versioned
mkdir -p ${SNAP_DATA}/etc/spark
cp -a ${SNAP}/etc/spark/conf.dist ${SNAP_DATA}/etc/spark

# if we dont have config yet, link the dist config
SPARK_CONF_DIR=${SNAP_DATA}/etc/spark/conf
if [ ! -e ${SPARK_CONF_DIR} ]; then
  ln -s conf.dist ${SPARK_CONF_DIR}

  # use our spark-env that understands SNAP[_DATA|_COMMON]
  cp ${SNAP}/snap/sources/spark-env.sh ${SPARK_CONF_DIR}

  # setup derby metastore location
  if [ ! -e ${SPARK_CONF_DIR}/spark-defaults.conf ]; then
    cp ${SPARK_CONF_DIR}/spark-defaults.conf.template ${SPARK_CONF_DIR}/spark-defaults.conf
  fi
  # location must be writable by everyone
  mkdir -p ${SNAP_COMMON}/derby && chmod 777 ${SNAP_COMMON}/derby
  echo "spark.driver.extraJavaOptions -Dderby.system.home=${SNAP_COMMON}/derby" >> \
    ${SPARK_CONF_DIR}/spark-defaults.conf
fi
